name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.7.0'
        arch: 'win64_msvc2019_64'
        dir: '${{ runner.workspace }}/Qt'

    - name: Configure
      run: |
        echo "QTDIR=${{ runner.workspace }}/Qt/6.7.0/msvc2019_64" >> $GITHUB_ENV
        echo "${{ runner.workspace }}/Qt/6.7.0/msvc2019_64/bin" >> $GITHUB_PATH
        qmake -tp vc -r

    - name: Build
      run: |
        msbuild /m /p:Configuration=Release
