name: Build and Package QT Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install QT
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.7.0'
        arch: 'win64_msvc2019_64'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild Train\Train.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
    
    - name: Package
      run: |
        cd Train\x64\Release
        windeployqt TrainMainApp.exe --qmldir ../../

    - name: Create Zip
      uses: papeloto/action-zip@v1
      with:
        files: Train\x64\Release
        recursive: true
        zipname: bus.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: busRelease
        path: bus.zip