name: Build and Package QT Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: ..
  QT_VERSION:   6.7.0
  BUILD_CONFIGURATION: Release

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install QT
      uses: jurplel/install-qt-action@v4
      with:
        version:      ${{ env.QT_VERSION }}
        host:         windows
        target:       desktop
        arch:         win64_msvc2019_64
        dir:          ${{ runner.temp }}
        setup-python: false 
        set-env:      true
        cache:        true
    
    - name: Print Qt version information
      run: |
        qmake -v
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Create build folder
      run: |
          mkdir -p ${{ runner.temp }}\build
    
    - name: Set Qt Environment Variables
      run: |
          echo "Setting Qt Environment Variables"
          echo "QTDIR=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64" >> $GITHUB_ENV
          echo "QtToolsPath=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64/bin" >> $GITHUB_ENV
          echo "QtMsBuild=%LOCALAPPDATA%\QtMsBuild" >> $GITHUB_ENV
          ls "${{ runner.temp }}/Qt/"
      shell: bash

  build:
    needs: setup
    runs-on: windows-latest

    steps:
    - name: Build app for release
      working-directory: ${{ github.workspace }}
      run: |
        echo "Current directory: $($PWD.Path)"
        msbuild /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:OutDir=${{ runner.temp }}\build\ "Train.sln"

  package:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Package
      working-directory: ${{ runner.temp }}/build
      run: |
        windeployqt TrainMainApp.exe --qmldir ${{ github.workspace }}\Train

    - name: Create Zip
      uses: papeloto/action-zip@v1
      with:
        files: |
          ${{ runner.temp }}/build/*
        recursive: true
        dest: build.zip

  upload:
    needs: package
    runs-on: windows-latest

    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: busRelease
        path: ${{ runner.temp }}/build.zip